Spec basic instructions
WebAssembly/threads pull request #170
Opened 2020-11-18 15:57 UTC by rossberg

This updates the spec for load, store, memory.size & .grow instructions.

* Extend formal rules to allow atomic instructions on unshared memory.
* Update prose spec.
* Some fixes.

2020-11-18 16:26 UTC, rossberg commented
Unfortunately, it looks like MathJax is messing up the notation pretty badly. I tried a few quick hacks, but to no avail. Leaving that problem for later.

2020-11-19 17:28 UTC, rossberg commented
@conrad-watt, PTAL.

2020-11-21 14:42 UTC, conrad-watt requested changes
Main issue currently is the behaviour of `cmpxchg`.

After this PR, I believe the next steps are to add `fence` and flesh out the semantics of `wait/notify`?

2020-11-21 14:42 UTC, conrad-watt commented on document/core/exec/instructions.rst
> +   The alignment :math:`\memarg.\ALIGN` in load and store instructions does not affect the semantics of accesses to :ref:`unshared <syntax-unshared>` :ref:`memories <syntax-mem>`.
Even for shared memories, non-atomic accesses are allowed to have incorrect alignment hints, I think?

2020-11-21 14:42 UTC, conrad-watt commented on document/core/exec/instructions.rst
> +:math:`t\K{.}\LOAD{N}(\K{\_}\sx)^?~\memarg`
I think the _`N`_ should be inside the option bracket?

2020-11-21 14:42 UTC, conrad-watt commented on document/core/exec/instructions.rst
> +   a. Perform the :ref:`action <syntax-act>` :math:`(\ARD~a.\LLEN~n)` to read the length :math:`n` of the shared :ref:`memory instance <syntax-meminst>` at :ref:`memory address <syntax-memaddr>` :mat
The read action here should be atomic/sc.

2020-11-21 14:42 UTC, conrad-watt commented on document/core/exec/instructions.rst
> +      i. Perform the :ref:`action <syntax-act>` :math:`(\ARD~a.\LLEN~l)` to read the length :math:`l` of the shared :ref:`memory instance <syntax-meminst>` at :ref:`memory address <syntax-memaddr>` :
The read here should be atomic/sc.

2020-11-21 14:42 UTC, conrad-watt commented on document/core/exec/instructions.rst
> +    c. Perform the atomic :ref:`action <syntax-act>` :math:`(\ARMW_{\ord}~a.\LDATA[\X{ea}]~b_{\F{r}}^\ast~b_{\F{r}}^\ast)` to read the bytes :math:`b_{\F{r}}^\ast` from data offset :math:`\X{ea}` of
The _`ord`_ subscript is never defined (should just be atomic/sc).

2020-11-21 14:42 UTC, conrad-watt commented on document/core/exec/instructions.rst
> +    c. Perform the atomic :ref:`action <syntax-act>` :math:`(\ARMW_{\ord}~a.\LDATA[\X{ea}]~b_{\F{r}}^\ast~b_{\F{r}}^\ast)` to read the bytes :math:`b_{\F{r}}^\ast` from data offset :math:`\X{ea}` of
Also, `b_r*` seems to be repeated twice when the second component should be `b_w*` (copy-paste nit).

2020-11-21 14:42 UTC, conrad-watt commented on document/core/exec/instructions.rst
> +    c. Perform the atomic :ref:`action <syntax-act>` :math:`(\ARMW_{\ord}~a.\LDATA[\X{ea}]~b_{\F{r}}^\ast~b_{\F{r}}^\ast)` to read the bytes :math:`b_{\F{r}}^\ast` from data offset :math:`\X{ea}` of
rmw copy-paste nit replicated here (although as described above this section needs to change).

2020-11-21 14:42 UTC, conrad-watt commented on document/core/exec/instructions.rst
> +:math:`t\K{.}\ATOMICRMW({N}\K{\_u})^?\K{.}\ATCMPXCHG~\memarg`
High-level:

cmpxchg should only perform an rmw action if the comparison succeeds. This means that at the operational level, the instruction non-deterministically either emits an atomic read action where the observed value is != the argument, or an rmw action where the read value is == the argument.

2020-11-21 14:42 UTC, conrad-watt commented on document/core/exec/instructions.rst
> +11. If :math:`N` and :math:`\sx` are part of the instruction, then:
can conditionals like this be factored more like the formal semantics?

i.e. have a few preamble lines that state
"1. N = |t| if N is not part of the instruction"

some of the RMWs especially have a lot of case-splitting in the text on this

2020-11-21 14:42 UTC, conrad-watt commented on document/core/exec/instructions.rst
> +   a. Either:
the "try growing memory" text in the non-shared case above was always informal language. Could some of that flavour be added to this case too? i.e.

```
a. Either:
  memory growth succeeds.
  ... let bla bla bla
b. Or:
  memory growth fails.
  ... bla bla bla
```

2020-11-21 23:59 UTC, conrad-watt commented on document/core/exec/instructions.rst
> +:math:`t\K{.}\ATOMICRMW({N}\K{\_u})^?\K{.}\ATCMPXCHG~\memarg`
Huh, the JS spec also models compareExchange as an rmw even if the comparison fails. I'll double check, but I'm pretty sure that's not correct.

2020-11-22 00:04 UTC, conrad-watt commented on document/core/exec/instructions.rst
> +:math:`t\K{.}\ATOMICRMW({N}\K{\_u})^?\K{.}\ATCMPXCHG~\memarg`
C++11 models it as just a load in the failure case, so I think this is also a JS spec bug.

2020-11-23 14:14 UTC, rossberg reviewed
Thanks for the thorough review! Yes, I think the next steps will be wait/notify/fence. Do you want to proceed with those?

2020-11-23 14:14 UTC, rossberg commented on document/core/valid/instructions.rst
> +     C \vdash \MEMORYATOMICNOTIFY~\memarg : [\I32~\I64] \to [\I64]
Yes, the current reduction rules also match that, fixed.

However, the reduction rule for wait seem to have the operand order reversed relative to both validation and overview. Added a todo.

2020-11-25 16:39 UTC, conrad-watt reviewed
Just a few nits.

I can look at fence/wait/notify in the next couple of weeks, but I really need to submit my thesis so I'm finding it hard to manage my time.

2020-11-25 16:44 UTC, conrad-watt commented on document/core/exec/instructions.rst
> +    a. Perform the :ref:`action <syntax-act>` :math:`(\ARD~a.\LLEN~n)` to read the length :math:`n` of the shared :ref:`memory instance <syntax-meminst>` at :ref:`memory address <syntax-memaddr>` :ma
sorry, this comment should have been at line 439 just below

2020-11-26 08:18 UTC, rossberg reviewed
Thanks! No stress, I thought your thesis was already due in September.

2020-11-26 08:18 UTC, rossberg commented on document/core/exec/instructions.rst
> +   a. Let :math:`\X{st}` be the :ref:`pro forma type <aux-bytes>` :math:`\iN`.
Updated.

2020-11-26 08:18 UTC, rossberg commented on document/core/exec/instructions.rst
> +    a. Perform the :ref:`action <syntax-act>` :math:`(\ARD~a.\LLEN~n)` to read the length :math:`n` of the shared :ref:`memory instance <syntax-meminst>` at :ref:`memory address <syntax-memaddr>` :ma
Made explicit in the prose. In the formal semantics that's implicit by the side conditions, particularly, its use as an argument to bytes^-1.

2020-11-26 08:18 UTC, rossberg commented on document/core/exec/instructions.rst
> +   a. Let :math:`\X{st}` be the :ref:`pro forma type <aux-bytes>` :math:`\iN`.
Fixed.

2020-11-26 08:18 UTC, rossberg commented on document/core/exec/instructions.rst
> +   a. Let :math:`\X{st}` be the :ref:`pro forma type <aux-bytes>` :math:`\iN`.
Fixed.

2020-11-26 08:18 UTC, rossberg commented on document/core/exec/instructions.rst
> +    c. Perform the atomic :ref:`action <syntax-act>` :math:`(\ARMW_{\SEQCST}~a.\LDATA[\X{ea}]~b_{\F{r}}^\ast~b_{\F{w}}^\ast)` to read the bytes :math:`b_{\F{r}}^\ast` from data offset :math:`\X{ea}`
Fixed as above. (Yes, for b*_w this follows from the definition of bytes_st.)

2020-11-26 08:18 UTC, rossberg commented on document/core/exec/instructions.rst
> +     \wedge & b_{\F{r}}^\ast = \bytes_{\X{st}}(\wrapt_{t,\X{st}}(\atop_t(c_1, c_2)))) \\
Fixed.

2020-11-26 08:18 UTC, rossberg commented on document/core/exec/instructions.rst
> +   a. Let :math:`\X{st}` be the :ref:`pro forma type <aux-bytes>` :math:`\iN`.
Fixed.

2020-11-26 08:18 UTC, rossberg commented on document/core/exec/instructions.rst
> +    c. Perform the atomic :ref:`action <syntax-act>` :math:`(\ARMW_{\SEQCST}~a.\LDATA[\X{ea}]~b_{\F{r}}^\ast~b_{\F{w}}^\ast)` to read the bytes :math:`b_{\F{r}}^\ast` from data offset :math:`\X{ea}`
Fixed.

2020-11-26 10:40 UTC, conrad-watt commented
> Thanks! No stress, I thought your thesis was already due in September.

yes

2020-11-27 17:04 UTC, conrad-watt approved these changes
LGTM

2020-11-30 07:57 UTC, merged